my_app/my_app/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("user.urls")),
    path('', include('post.urls')),
]

if settings.DEBUG:
  urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

my_app/post/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from user.views import SignUpView, LoginView
from . import views


urlpatterns = [
    path('', views.posts, name="posts"),
    # path('posts/<int:post_id>/', views.posts_view, name="post_list"),
    path("create/", views.create, name="create"),
    path("edit/<int:post_id>/", views.edit_post, name="edit_post"),
    path("<int:pk>/delete", views.PostDeleteView.as_view(), name="post_delete"),
]

my_app/user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from user.views import SignUpView, LoginView
from . import views


urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path("accounts/logout/", LogoutView.as_view(), name="logout")

]

my_app/post/models.py
from django.db import models
from user.models import MyUser


class Post(models.Model):
    SUBJECTS=(
        ('English',"English"),
        ("Russian","Russian"),
        ("Math","Math"),
        ("History","History"),
        ('Belarusian',"Belarusian"),
        ('Chemistry',"Chemistry"),
        ('Physics',"Physics")
    )
    CHOICES=(
        ('+',"+"),
        ("-","-")
    )
    TIME=(
        ('30',"30"),
        ("45","45"),
        ("60","60"),
        ("90","90"),
    )

    image = models.ImageField(null=False, blank=False, upload_to="images")
    first_name = models.CharField(max_length=100, null=False, blank=False)
    second_name = models.CharField(max_length=100, null=False, blank=False)
    subject = models.CharField(max_length=100, choices=SUBJECTS, default="English", null=False, blank=False)
    about = models.TextField(max_length=500, blank=True, null=True)
    qualification = models.CharField(max_length=200, null=False, blank=False)
    work_experience = models.CharField(max_length=300, null=False, blank=False, )
    organizations = models.CharField(max_length=300, null=False, blank=False)
    address = models.CharField(max_length=100, null=False, blank=False, )
    online_lessons = models.CharField(max_length=100, choices=CHOICES, default="+", null=False, blank=False)
    offline_lessons = models.CharField(max_length=100, choices=CHOICES, default="+", null=False, blank=False)
    lessons_at_home = models.CharField(max_length=100, choices=CHOICES, default="+", null=False, blank=False)
    price = models.PositiveIntegerField(null=False, blank=False)
    time_of_lesson = models.CharField(choices=TIME, default="60", null=False, blank=False)
    add_information = models.CharField(max_length=100, null=True, blank=True)

my_app/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class MyUser(AbstractUser):
    email = models.EmailField(unique=True, max_length=110)
    phone = models.CharField(max_length=14, blank=True, null=True)
    first_name = models.CharField(max_length=40, blank=True, null=True)
    last_name = models.CharField(max_length=40, blank=True, null=True)

my_app/post/forms.py
from django import forms
from post.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("image","first_name","second_name",
                  "subject",
                  "about",
                  "qualification",
                  "work_experience",
                  "organizations",
                  "address",
                  "online_lessons",
                  "offline_lessons",
                  "lessons_at_home",
                  "price",
                  "add_information",)

my_app/user/forms.py
from django import forms
from user.models import MyUser


class CustomUserCreationForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ("username","password","email","groups","first_name","last_name","phone")

my_app/post/views.py
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DeleteView
from post.forms import PostForm
from post.models import Post


def posts(request):
    search_query = request.GET.get("search", "")
    if search_query:
        posts = Post.objects.filter(title__icontains=search_query)
    else:
        posts = Post.objects.all().order_by("id")
    all_images = Post.objects.all()
    return render(request, "posts.html", {"posts": posts, "all_images": all_images})




# def posts_view(request, post_id):
#     post = get_object_or_404(Post, id=post_id)
#     return render(request, "posts_view.html", {"post": post})


@permission_required(perm="post.add_post", raise_exception=True)
def create(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.my_user = request.user
            post.save()
            form.save_m2m()
            return redirect("/")
        else:
            return redirect("/")
    else:
        form = PostForm()
    return render(request, "create.html", {"form": form})




def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.custom_user:
        return redirect(f"/posts/{post_id}/")
    if request.method == "GET":
        form = PostForm(instance=post)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
        return redirect("posts")
    return render(request, "edit_post.html", {"form": form, "post": post})


class PostDeleteView(DeleteView):
    model = Post
    success_url = "posts"
    template_name = "delete_post.html"

my_app/user/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import request
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.models import Group
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView
from django.contrib.auth import authenticate, login, logout
from user.forms import CustomUserCreationForm
from user.models import MyUser


# def users(request):
#     users_list = MyUser.objects.all()
#     paginator=Paginator(users_list,5)
#     page_number=request.GET.get('page',1)
#     users=paginator.page(page_number)
#     return render(request, "UsersList.html", {"users": users})


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'signup.html'

    def post(self, request, *args, **kwargs):
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            # user_group = Group.objects.get()
            # user.groups.add(user_group)
            return redirect("/")
        else:
            return render(request, self.template_name, {'form': form})


class LoginView(LoginView):
    template_name = 'login.html'

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('/')
        return self.render_to_response(self.get_context_data())

my_app/post/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head >
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <div class="container">
      <header class="border-bottom lh-1 py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
                    {% block add %}{% endblock %}
          {% if perms.post.change_post %}
         <button type="submit" class="nav-link btn btn-link"></button>
                 <style="display: inline; border: none; background: none; box-shadow: none;"><a   href="{% url "create" %}" style="color:black" >Create post</a></button>
         <link rel="shortcut icon" href="#" />
          {% endif %}
      </div>
      <div class="col-4 text-center">
          <h3><a class="blog-header-logo text-body-emphasis text-decoration-none"  style="color:black" >Users</a></h3>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="link-secondary" href="#" aria-label="Search">

             <input class="search" type="text" name="search">
            <button type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"></circle><path d="M21 21l-5.2-5.2"></path></svg></button>
            </form>
            <style>
                body {
                    background: lavenderblush;
                    color: dimgrey;
                    font-family: "Times New Roman";
                }
            </style>
        </a>
        {% if request.user.is_authenticated  %}
            <form action="{% url 'logout' %}" method="post" class="form-inline">
                {% csrf_token %}
                <button type="submit" class="nav-link btn btn-link" style="color:black"
                        style="display: inline; border: none; background: none; box-shadow: none;">LogOut
                </button>
            </form>
            {% else %}
      <ul class="nav">
        <li class="nav-item"><a  class="btn btn-sm btn-outline-secondary" href="{% url "signup" %}" style="color:black"
            class="nav-link link-body-emphasis px-2">SignUp</a></li>
        <li class="nav-item"><a class="btn btn-sm btn-outline-secondary"  href="{% url "login" %}" style="color:black" class="nav-link link-body-emphasis px-2">LogIn</a></li>
      </ul>
     {% endif %}
      </div>
    </div>
  </header>
    </div>
</head>
<body bgcolor="blue">
{% block content %}
{% endblock %}
</body>
</html>

my_app/post/templates/create.html
{% extends "base.html" %}
{% block content %}
<link rel="shortcut icon" href="#" />
<div class="container">
     <h2>Create Post</h2>
<form method="post" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <link rel="icon" href="media/images/favicon.ico">
    <button type="subbmit" class="save bth-default">Save</button>
</form>
</div>
{% endblock %}

my_app/post/templates/delete_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<h2>Are you sure you want to delete this post ?</h2>
<form method="post">
    {% csrf_token %}
    <button class="btn btn-success" type="submit">Delete</button>
     <a  href="{% url "posts" %}">Back</a>
</form>
</div>

{% endblock %}

my_app/post/templates/edit_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
     <h2>Edit Post</h2>
<form method="post" class="post-form" >
    {% csrf_token %}
    {{form.as_p}}
    <button type="subbmit" class="save bth-default">Save</button>
    <a href="{% url "post_delete" post.id%}">Delete</a>
</form>
{% endblock %}

my_app/post/templates/posts.html
{% extends "base.html" %}
{% block content %}
{% for post in posts %}
<div class="container" >
    <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
               <img class="img-article-left" src="{{post.image.url}}" width="600px"  height="550" align="left" />
              <h2 class="card-text">{{post.title}}</h2>
                <p>{{post.text}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a  style="color:black">View</a></button>
                    {% if post.custom_user == request.user %}
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url "edit_post" post_id=post.id %}" style="color:black">Edit</a></button>
                    {% endif %}
                </div>
                <small class="text-body-secondary"> {{post.created_at}}</small>
              </div>
              </div>
            </div>
          </div>
        </div>


{% endfor %}
{% endblock %}

my_app/user/templates/UsersList.html
{% extends "base.html" %}
{% block content %}
<div class="container">
{% for user in users %}
<p>{{ user.email }}</p>
{% endfor %}
</div>
<div class ="container">{% include "pagination.html" with page=users %}</div>
{% endblock content %}

my_app/user/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Enter</button>
        </form>
    </div>
{% endblock %}

my_app/user/templates/pagination.html
<div class="pagination"> <span class="step-links">
    <div class="container">
{% if page.has_previous %}
<a href="?page={{ page.previous_page_number }}">Previous</a>
{% endif %}
<span class="current">
Page {{ page.number }} of {{ page.paginator.num_pages }}.
</span>
{% if page.has_next %}
<a href="?page={{ page.next_page_number }}">Next</a>
{% endif %}
    </div>
</span> </div>

my_app/user/templates/signup.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Enter</button>
        </form>
    </div>
{% endblock %}